version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    # effectively remove limit
    open-pull-requests-limit: 100
    ignore:
      # handled via `yarn dlx @turbo/codemod@latest update`
      - dependency-name: 'turbo'
      - dependency-name: '@vercel/turbo'

      # ignore odd versions as they will never become LTS
      - dependency-name: "@types/node"
        versions: [ "25.*", "27.*", "29.*", "31.*", "33.*", "35.*", "37.*" ]

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
