version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 3
      semver-major-days: 3

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 3
      semver-major-days: 3
    # effectively remove limit
    open-pull-requests-limit: 100
    ignore:
      # ignore odd versions as they will never become LTS
      - dependency-name: "@types/node"
        versions: [ "25.*", "27.*", "29.*", "31.*", "33.*", "35.*", "37.*" ]

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 3
      semver-major-days: 3
